spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/eTracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:speedislive}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth2 Configuration
# You must replace these with your own credentials from the Google Cloud Console
spring.security.oauth2.client.registration.google.client-id=360910639065-mtiq76fgpdj53keeejdf4fmcpfkqlsih.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
